export interface CuratedCameraSource {
  id: string;
  lat: number;
  lng: number;
  name: string;
  city: string;
  country: string;
  feed_url?: string;
  external_url?: string;
  stream_url?: string;
  stream_type?: 'jpg' | 'hls' | 'iframe' | 'mjpeg' | 'mp4';
  source: string;
}

export function getFallbackGlobalCameraSources(): CuratedCameraSource[] {
  return [
    {
      id: 'earthcam-times-square',
      lat: 40.7580,
      lng: -73.9855,
      name: 'Times Square Live',
      city: 'New York',
      country: 'US',
      external_url: 'https://www.earthcam.com/usa/newyork/timessquare/?cam=tsqcam',
      source: 'EarthCam',
    },
    {
      id: 'earthcam-las-vegas',
      lat: 36.1146,
      lng: -115.1728,
      name: 'Las Vegas Strip',
      city: 'Las Vegas',
      country: 'US',
      external_url: 'https://www.earthcam.com/usa/nevada/lasvegas/?cam=bellagio',
      source: 'EarthCam',
    },
    {
      id: 'earthcam-waikiki',
      lat: 21.2765,
      lng: -157.8230,
      name: 'Waikiki Beach',
      city: 'Honolulu',
      country: 'US',
      external_url: 'https://www.earthcam.com/usa/hawaii/honolulu/waikiki/?cam=waikiki',
      source: 'EarthCam',
    },
    {
      id: 'earthcam-sydney-harbor',
      lat: -33.8568,
      lng: 151.2153,
      name: 'Sydney Harbour',
      city: 'Sydney',
      country: 'Australia',
      external_url: 'https://www.earthcam.com/australia/sydney/?cam=sydneyharbour',
      source: 'EarthCam',
    },
    {
      id: 'earthcam-london-eye',
      lat: 51.5033,
      lng: -0.1195,
      name: 'London Eye',
      city: 'London',
      country: 'UK',
      external_url: 'https://www.earthcam.com/uk/london/londoneye/',
      source: 'EarthCam',
    },
    {
      id: 'earthcam-paris',
      lat: 48.8584,
      lng: 2.2945,
      name: 'Paris Eiffel Tower',
      city: 'Paris',
      country: 'France',
      external_url: 'https://www.earthcam.com/europe/france/paris/',
      source: 'EarthCam',
    },
    {
      id: 'earthcam-rome',
      lat: 41.9022,
      lng: 12.4964,
      name: 'Rome Historic Center',
      city: 'Rome',
      country: 'Italy',
      external_url: 'https://www.earthcam.com/europe/italy/rome/',
      source: 'EarthCam',
    },
    {
      id: 'earthcam-tokyo',
      lat: 35.6895,
      lng: 139.6917,
      name: 'Tokyo Shibuya',
      city: 'Tokyo',
      country: 'Japan',
      external_url: 'https://www.earthcam.com/asia/japan/tokyo/',
      source: 'EarthCam',
    },
    {
      id: 'earthcam-dubai',
      lat: 25.2048,
      lng: 55.2708,
      name: 'Dubai Marina',
      city: 'Dubai',
      country: 'UAE',
      external_url: 'https://www.earthcam.com/asia/uae/dubai/',
      source: 'EarthCam',
    },
    {
      id: 'earthcam-cape-town',
      lat: -33.9249,
      lng: 18.4241,
      name: 'Cape Town Waterfront',
      city: 'Cape Town',
      country: 'South Africa',
      external_url: 'https://www.earthcam.com/africa/southafrica/capetown/',
      source: 'EarthCam',
    },
    {
      id: 'earthcam-berlin',
      lat: 52.5200,
      lng: 13.4050,
      name: 'Berlin Alexanderplatz',
      city: 'Berlin',
      country: 'Germany',
      external_url: 'https://www.earthcam.com/europe/germany/berlin/',
      source: 'EarthCam',
    },
    {
      id: 'earthcam-madrid',
      lat: 40.4168,
      lng: -3.7038,
      name: 'Madrid Plaza Mayor',
      city: 'Madrid',
      country: 'Spain',
      external_url: 'https://www.earthcam.com/europe/spain/madrid/',
      source: 'EarthCam',
    },
    {
      id: 'earthcam-mexico-city',
      lat: 19.4326,
      lng: -99.1332,
      name: 'Mexico City Zócalo',
      city: 'Mexico City',
      country: 'Mexico',
      external_url: 'https://www.earthcam.com/latinamerica/mexico/mexicocity/',
      source: 'EarthCam',
    },
    {
      id: 'earthcam-sao-paulo',
      lat: -23.5505,
      lng: -46.6333,
      name: 'São Paulo Avenida Paulista',
      city: 'São Paulo',
      country: 'Brazil',
      external_url: 'https://www.earthcam.com/latinamerica/brazil/saopaulo/',
      source: 'EarthCam',
    },
    {
      id: 'youtube-live-nyc',
      lat: 40.7128,
      lng: -74.0060,
      name: 'New York City Waterfront',
      city: 'New York',
      country: 'US',
      stream_url: 'https://www.youtube.com/embed/ScMzIvxBSi4?autoplay=1&mute=1',
      stream_type: 'iframe',
      source: 'YouTube Live',
    },
    {
      id: 'youtube-live-london',
      lat: 51.5074,
      lng: -0.1278,
      name: 'Central London Live',
      city: 'London',
      country: 'UK',
      stream_url: 'https://www.youtube.com/embed/5qap5aO4i9A?autoplay=1&mute=1',
      stream_type: 'iframe',
      source: 'YouTube Live',
    },
  ];
}
